### ISSUE TITLE
Visualise with the controller does not work

### ISSUE THREAD

**Issue by yj-Tang** [JamieMair/MuJoCo.jl#83]
Hi, I try out the example [https://github.com/JamieMair/MuJoCo.jl/blob/main/examples/visualise.jl](url) and [https://github.com/JamieMair/MuJoCo.jl/blob/main/examples/humanoid_lqr.jl](url). It seems that the visualizer only works in the PassiveDynamics mode which can not visualize the trajectory with a controller. 

[visualise!(model, data, controller=humanoid_ctrl!)](https://github.com/JamieMair/MuJoCo.jl/blob/32a25ed3c8c15f43e6a56e082422dc99f0c9a426/examples/humanoid_lqr.jl#L170C1-L170C51) and [visualise!(model, data, trajectories = [states, ctrl_states])](https://github.com/JamieMair/MuJoCo.jl/blob/32a25ed3c8c15f43e6a56e082422dc99f0c9a426/examples/visualise.jl#L30C1-L30C62) do not work.

Or is there a way to switch to the controlled mode? 

Thanks for providing the nice wrapper. Looking forward to your reply.

Best regards,
Yujie

**Comment by JamieMair** [comment]
Hi thanks for your comment!

I've linked to an issue so that we can improve the docs and interface for future users.

For now, you switch between passive and controller by using "Ctrl+Right Arrow" or "Ctrl+Left Arrow". These controls are in the help message that you can see in the REPL (/terminal) by pressing F1 in the launched window.

**Comment by yj-Tang** [comment]
Ah! I see. Thanks for the quick reply!
